changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: CI & Build
      labels:
        - ci
        - build
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
