name: Build and Upload Kural Tab

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  build-extension:
    name: Build Chrome Extension Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Create Dist Directory
        run: mkdir -p dist

      - name: Copy Relevant Files to Dist
        run: rsync -av --progress src/ dist/ --exclude=".git" --exclude="node_modules" --exclude="tests" --exclude=".*"

      - name: List Files in Dist (Debugging)
        run: ls -la dist

      - name: Zip Chrome Extension Artifact
        run: zip -r kural-tab-${{ github.sha }}.zip dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kural-tab-${{ github.sha }}
          path: kural-tab-${{ github.sha }}.zip
          retention-days: 5

  upload-extension:
    name: Upload Extension
    runs-on: ubuntu-latest
    needs: build-extension
    env:
      EXTENSION_ID: <extension id here>

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download Bundle Artifact
        uses: actions/download-artifact@v4
        with:
          name: kural-tab-${{ github.sha }}

      - name: Install Webstore CLI
        run: npm install -g chrome-webstore-upload-cli

      - name: Upload to Chrome Web Store
        run: |
          chrome-webstore-upload upload \
            --source kural-tab-${{ github.sha }}.zip \
            --extension-id ${{ env.EXTENSION_ID }} \
            --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \
            --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \
            --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
