name: Build and Upload Kural Tab

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  build-extension:
    uses: ./.github/workflows/build.yml
    with:
      artifact_name: kural-tab-${{ github.sha }}
      retention_days: 20

  upload-extension:
    name: Upload Extension
    runs-on: ubuntu-latest
    needs: build-extension
    env:
      EXTENSION_ID: njidhifbpgbfadoffhibkjnnkfhcglpc

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download Unzipped Artifact
        uses: actions/download-artifact@v4
        with:
          name: kural-tab-${{ github.sha }}
          path: dist/

      - name: Zip Extension for Chrome Web Store
        run: zip -r kural-tab.zip dist/

      - name: Install Webstore CLI
        run: npm install -g chrome-webstore-upload-cli

      - name: Upload to Chrome Web Store
        run: |
          chrome-webstore-upload upload \
            --source kural-tab.zip \
            --extension-id ${{ env.EXTENSION_ID }} \
            --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \
            --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \
            --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
