name: Update Chrome Extension

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  build-chrome-extension:
    name: Build Chrome Extension Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |-
          zip -r chrome-extension-${{ github.sha }}.zip dist

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.sha }}.zip
          retention-days: 1  # Optional: Set retention duration for artifacts

  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension
    env:
      EXTENSION_ID: <extension id here>

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Install webstore CLI
        run: |-
          npm install -g chrome-webstore-upload-cli

      - name: Upload step
        run: |-
          chrome-webstore-upload upload \
            --source chrome-extension-${{ github.sha }}.zip \
            --extension-id ${{ env.EXTENSION_ID }} \
            --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \
            --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \
            --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
