name: PR Comment with Build Links

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build-extension:
    uses: ./.github/workflows/build.yml
    with:
      artifact_name: kural-tab-${{ github.event.pull_request.number }}
      retention_days: 3

  comment-pr:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs: build-extension
    permissions:
      pull-requests: write
    steps:
      - name: Delete Old PR Comments
        uses: thollander/actions-comment-pull-request@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-tag: build-preview  
          delete: true 

      - name: Post New PR Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-tag: build-preview
          message: |
            🚀 **Preview Build Available for Testing**  
            Thanks for your contribution! Here are some useful links:

            🔗 **Download Build**: [Artifacts Page](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Let us know if you have any feedback! 🚀
