name: PR Comment with Direct Artifact Link

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize  # Runs when new commits are pushed to the PR

jobs:
  build-extension:
    uses: ./.github/workflows/build.yml
    with:
      artifact_name: kural-tab-${{ github.event.pull_request.number }}
      retention_days: 3

  comment-pr:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs: build-extension
    permissions:
      pull-requests: write  # Allows posting PR comments
    steps:
      - name: Get Latest Artifact ID
        id: get-artifact
        run: |
          ARTIFACT_ID=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts --jq '.artifacts[] | select(.name == "kural-tab-${{ github.event.pull_request.number }}") | .id')
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR Comment with Direct Download Link
        uses: thollander/actions-comment-pull-request@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            🚀 **Preview Build Available for Testing**  
            Thanks for your contribution! Here’s the direct download link to the artifact:

            📦 **[Download Extension](https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts/${{ env.ARTIFACT_ID }})**  

            Let us know if you have any feedback! 🚀
